version: '3.1'

services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: skizztv191
      MYSQL_DATABASE: db-nfc-game
      MYSQL_USER: xenon
      MYSQL_PASSWORD: skizztv191
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro

  fast_api:
    build: ./fast_api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./fast_api/:/app/
    depends_on:
      - mysqldb
    ports:
      - '8000:8000'
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysqldb
      PMA_USER: xenon
      PMA_PASSWORD: skizztv191
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    restart: always
